#include "config.h"

namespace passgfw {

std::vector<std::string> Config::GetBuiltinURLs() {
    return {
        "http://localhost:8080/passgfw",      // Local testing (HTTP)
        "http://127.0.0.1:8080/passgfw",      // Alternative local (HTTP)
        "https://example.com/passgfw?platform=mobile",
        "https://backup.example.com/check",
        // Special URL: Fetch additional URL list (ends with #)
        "https://example.com/list.txt#"
    };
}

// Public key is embedded at build time
const char* Config::GetPublicKey() {
    // AUTO-GENERATED - DO NOT EDIT MANUALLY
    // Generated by embed_public_key.sh
    static const char* PUBLIC_KEY = R"(
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmCrvKUld4fDQ91mgfNmp
RvVQc0Zb/jOXDPtTj8jO1Q2I1l4QGYSw1jIrHnExoPfOhQoAOmqnALrQwgPh4uiW
heUSkC7Kj3M47VfDoe/gIw7mtunqwPZlVY3warLTdvbpWgDb8gExRs+HzbVSX3FQ
ilD4bw1P/BvXVRs+eyQ/GItraH0FWjUma2yNPrbkJiqYAiPeoIgNGxG4NKOGL5UZ
1RwfPr1i0++7ys8NFjQwDs4/IOmFCdrAlfQGUjLJ+fSciUiknyKH1giw/rEH8S96
9wkViAj4G3aLrDXuyb/zFsXfvr+QRhP0Mp2ua+euDpDyt6gaqnZZa4ZZ9NTDVFJd
ywIDAQAB
-----END PUBLIC KEY-----
)";
    
    return PUBLIC_KEY;
}

} // namespace passgfw
