package com.passgfw

/**
 * URL Entry with method, URL, and store flag
 */
data class URLEntry(
    val method: String,              // "api", "file", or "remove"
    val url: String,
    val store: Boolean = false       // 是否持久化存储（只对 api 和 file 有效，默认 false）
)

/**
 * Configuration for PassGFW
 */
object Config {
    // BUILD_CONFIG_START - Auto-generated by build script, DO NOT EDIT MANUALLY
    /**
     * Get built-in URL list
     * These URLs are generated during build from build_config.json
     */
    fun getBuiltinURLs(): List<URLEntry> {
        return listOf(
            URLEntry(method = "api", url = "http://localhost:8080/passgfw"),
            URLEntry(method = "api", url = "http://127.0.0.1:8080/passgfw")
        )
    }

    /**
     * Get public key (PEM format)
     * This key is embedded during build from ../server/keys/public_key.pem
     */
    fun getPublicKey(): String {
        return """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAywXbsHaPw9FWFQXVys4a
xABweET6hibzzAup+84Dacf3mUfGFYu6CBTuYni/x4r+WeiskiLQJSm1Bk80uWnn
OXcNRA7/LrxhXO91A+uwRgByO3PtkSODm9MAFhSCD+HUMdlLaeokQfK+BSLxPB9K
NzkU7HmdAVmLkqkyLxzXMg6BSK9dFoaYha/zz2ZpujCtGbk2FOSYBa+6zLFCnYer
URr4lR/9KAXM0Jjbc/6QdAoGcCSpFDMWJEFAwPPBAYot8XnqueTXYf9BRJHVPPj/
f9eGmPN6edFdnwdZev0a7KlxhgPIH2dBng9rPrG10vcbsf0w1+0JYI53jQB8vglG
rwIDAQAB
-----END PUBLIC KEY-----
        """.trimIndent()
    }
    // BUILD_CONFIG_END
    
    // Timeout settings
    const val REQUEST_TIMEOUT = 10_000L  // milliseconds
    const val RETRY_INTERVAL = 2_000L
    const val URL_INTERVAL = 500L
    
    // Retry settings
    const val MAX_RETRIES = 3
    const val RETRY_DELAY = 1_000L
    
    // Security limits
    const val MAX_LIST_RECURSION_DEPTH = 5
    const val NONCE_SIZE = 32
    const val MAX_CLIENT_DATA_SIZE = 200
}

