package com.passgfw

/**
 * URL Entry with method, URL, and store flag
 */
data class URLEntry(
    val method: String,              // "api", "file", or "remove"
    val url: String,
    val store: Boolean = false       // 是否持久化存储（只对 api 和 file 有效，默认 false）
)

/**
 * Configuration for PassGFW
 */
object Config {
    // BUILD_CONFIG_START - Auto-generated by build script, DO NOT EDIT MANUALLY
    /**
     * Get built-in URL list
     * These URLs are generated during build from build_config.json
     */
    fun getBuiltinURLs(): List<URLEntry> {
        return listOf(
            URLEntry(method = "api", url = "http://localhost:8080/passgfw")
        )
    }
    
    /**
     * Get public key (PEM format)
     * This key is embedded during build from ../server/keys/public_key.pem
     */
    fun getPublicKey(): String {
        return """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyLq8eCvXJ4kPxMd0c3oK
heUSkC7Kj3M47VfDoe/gIw7mtunqwPZlVY3warLTdvbpWgDb8gExRs+HzbVSX3FQ
x4LJD7yPOHn6wF/VqV5WzVp4Y3nMUx0dYYj3R4qJDnQr0yE3J6aDf8T8VJ/cLqGK
K+Q8Z3F5J8P7L6vXR5R6Y1LH4gT8qQp6h4kH6L3F5Y9J8R7qQ3p6H4kF8L6p5Y9J
8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7
L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6
F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5
QIDAQAB
-----END PUBLIC KEY-----
        """.trimIndent()
    }
    // BUILD_CONFIG_END
    
    // Timeout settings
    const val REQUEST_TIMEOUT = 10_000L  // milliseconds
    const val RETRY_INTERVAL = 2_000L
    const val URL_INTERVAL = 500L
    
    // Retry settings
    const val MAX_RETRIES = 3
    const val RETRY_DELAY = 1_000L
    
    // Security limits
    const val MAX_LIST_RECURSION_DEPTH = 5
    const val NONCE_SIZE = 32
    const val MAX_CLIENT_DATA_SIZE = 200
}

