package com.passgfw

/**
 * Configuration for PassGFW
 */
object Config {
    /**
     * Get built-in URL list
     */
    fun getBuiltinURLs(): List<String> {
        // TODO: Should be generated by build script
        return listOf(
            "http://localhost:8080/passgfw",
            "http://127.0.0.1:8080/passgfw"
        )
    }
    
    /**
     * Get public key (PEM format)
     */
    fun getPublicKey(): String {
        // TODO: Should be generated by build script
        return """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyLq8eCvXJ4kPxMd0c3oK
heUSkC7Kj3M47VfDoe/gIw7mtunqwPZlVY3warLTdvbpWgDb8gExRs+HzbVSX3FQ
x4LJD7yPOHn6wF/VqV5WzVp4Y3nMUx0dYYj3R4qJDnQr0yE3J6aDf8T8VJ/cLqGK
K+Q8Z3F5J8P7L6vXR5R6Y1LH4gT8qQp6h4kH6L3F5Y9J8R7qQ3p6H4kF8L6p5Y9J
8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7
L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6
F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5
QIDAQAB
-----END PUBLIC KEY-----
        """.trimIndent()
    }
    
    // Timeout settings
    const val REQUEST_TIMEOUT = 10_000L  // milliseconds
    const val RETRY_INTERVAL = 2_000L
    const val URL_INTERVAL = 500L
    
    // Retry settings
    const val MAX_RETRIES = 3
    const val RETRY_DELAY = 1_000L
    
    // Security limits
    const val MAX_LIST_RECURSION_DEPTH = 5
    const val NONCE_SIZE = 32
    const val MAX_CLIENT_DATA_SIZE = 200
}

