import Foundation

/// Configuration for PassGFW
struct Config {
    // MARK: - Built-in URLs and Keys
    
    /// Get built-in URL list
    /// These URLs will be auto-generated during build
    static func getBuiltinURLs() -> [String] {
        // TODO: This should be generated by build script from server public key
        return [
            "http://localhost:8080/passgfw",
            "http://127.0.0.1:8080/passgfw"
        ]
    }
    
    /// Get public key (PEM format)
    /// This key will be auto-generated during build
    static func getPublicKey() -> String {
        // TODO: This should be generated by build script
        return """
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyLq8eCvXJ4kPxMd0c3oK
        heUSkC7Kj3M47VfDoe/gIw7mtunqwPZlVY3warLTdvbpWgDb8gExRs+HzbVSX3FQ
        x4LJD7yPOHn6wF/VqV5WzVp4Y3nMUx0dYYj3R4qJDnQr0yE3J6aDf8T8VJ/cLqGK
        K+Q8Z3F5J8P7L6vXR5R6Y1LH4gT8qQp6h4kH6L3F5Y9J8R7qQ3p6H4kF8L6p5Y9J
        8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7
        L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6
        F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5Y9J8R7L6F5
        QIDAQAB
        -----END PUBLIC KEY-----
        """
    }
    
    // MARK: - Timeout Settings
    
    /// HTTP request timeout (seconds)
    static let requestTimeout: TimeInterval = 10
    
    /// Retry interval when all URLs fail (seconds)
    static let retryInterval: TimeInterval = 2
    
    /// Interval between URL checks (milliseconds)
    static let urlInterval: TimeInterval = 0.5
    
    // MARK: - Retry Settings
    
    /// Maximum number of retries per URL
    static let maxRetries = 3
    
    /// Delay between retries (milliseconds)
    static let retryDelay: TimeInterval = 1.0
    
    // MARK: - Security Limits
    
    /// Maximum nested list# depth
    static let maxListRecursionDepth = 5
    
    /// Random nonce size in bytes
    static let nonceSize = 32
    
    /// Maximum client_data length (RSA 2048 limit ~245 bytes for payload)
    static let maxClientDataSize = 200
}

